/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom08.bookstore;

/**
 *
 * @author Admin
 */
public class CashierFrame extends javax.swing.JFrame {

    /**
     * Creates new form CashierFrame
     */
    public CashierFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Header = new javax.swing.JPanel();
        lbl_userIcon = new javax.swing.JLabel();
        lbl_accountName = new javax.swing.JLabel();
        textFieldCustom1 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        panelCustom1 = new com.nhom08.bookstore.GUI.PanelCustom();
        jPanel1 = new javax.swing.JPanel();
        textFieldCustom2 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textFieldCustom3 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textFieldCustom4 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textFieldCustom5 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        textFieldCustom6 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        textFieldCustom7 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        textFieldCustom8 = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel8 = new javax.swing.JLabel();
        panel_cancelBtn = new com.nhom08.bookstore.GUI.PanelCustom();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 254, 251));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Header.setBackground(new java.awt.Color(219, 235, 247));
        panel_Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_filled.png"))); // NOI18N
        panel_Header.add(lbl_userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 12, 40, 40));

        lbl_accountName.setFont(new java.awt.Font("Lexend SemiBold", 0, 20)); // NOI18N
        lbl_accountName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_accountName.setText("Account name");
        panel_Header.add(lbl_accountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1098, 18, -1, -1));
        panel_Header.add(textFieldCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 11, 338, 41));

        getContentPane().add(panel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        panelCustom1.setBackground(new java.awt.Color(137, 207, 245));
        panelCustom1.setRoundBottomLeft(20);
        panelCustom1.setRoundBottomRight(20);
        panelCustom1.setRoundTopLeft(20);
        panelCustom1.setRoundTopRight(20);
        panelCustom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(137, 207, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldCustom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom2ActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 280, -1));

        jLabel1.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel1.setText("XXXXX.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelCustom1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, -1));

        jPanel2.setBackground(new java.awt.Color(137, 207, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldCustom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom3ActionPerformed(evt);
            }
        });
        jPanel2.add(textFieldCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 280, -1));

        jLabel2.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel2.setText("XXXXX.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelCustom1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, -1));

        jPanel3.setBackground(new java.awt.Color(137, 207, 245));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldCustom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom4ActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldCustom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 280, -1));

        jLabel3.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel3.setText("XXXXX.");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelCustom1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, -1));

        jPanel4.setBackground(new java.awt.Color(137, 207, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldCustom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom5ActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldCustom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 280, -1));

        jLabel4.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel4.setText("XXXXX.");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelCustom1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, -1));

        jPanel5.setBackground(new java.awt.Color(137, 207, 245));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldCustom6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom6ActionPerformed(evt);
            }
        });
        jPanel5.add(textFieldCustom6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 280, -1));

        jLabel6.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel6.setText("XXXXX.");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelCustom1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, -1));

        jPanel6.setBackground(new java.awt.Color(137, 207, 245));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldCustom7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom7ActionPerformed(evt);
            }
        });
        jPanel6.add(textFieldCustom7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 280, -1));

        jLabel7.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel7.setText("XXXXX.");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelCustom1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, -1));

        jPanel7.setBackground(new java.awt.Color(137, 207, 245));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldCustom8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCustom8ActionPerformed(evt);
            }
        });
        jPanel7.add(textFieldCustom8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 280, -1));

        jLabel8.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel8.setText("XXXXX.");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelCustom1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, -1));

        panel_cancelBtn.setRoundBottomLeft(20);
        panel_cancelBtn.setRoundBottomRight(20);
        panel_cancelBtn.setRoundTopLeft(20);
        panel_cancelBtn.setRoundTopRight(20);
        panel_cancelBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_item_cart.png"))); // NOI18N
        panel_cancelBtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 40, 38));

        panelCustom1.add(panel_cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 616, 50, 50));

        getContentPane().add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 85, 305, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCustom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom2ActionPerformed

    private void textFieldCustom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom3ActionPerformed

    private void textFieldCustom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom4ActionPerformed

    private void textFieldCustom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom5ActionPerformed

    private void textFieldCustom6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom6ActionPerformed

    private void textFieldCustom7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom7ActionPerformed

    private void textFieldCustom8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCustom8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCustom8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_accountName;
    private javax.swing.JLabel lbl_userIcon;
    private com.nhom08.bookstore.GUI.PanelCustom panelCustom1;
    private javax.swing.JPanel panel_Header;
    private com.nhom08.bookstore.GUI.PanelCustom panel_cancelBtn;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom1;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom2;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom3;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom4;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom5;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom6;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom7;
    private com.nhom08.bookstore.GUI.TextFieldCustom textFieldCustom8;
    // End of variables declaration//GEN-END:variables
}
