/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

/**
 *
 * @author Admin
 */
public class Panel_Statistics extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Statistics
     */
    public Panel_Statistics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelCustom1 = new Custom.PanelCustom();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelCustom2 = new Custom.PanelCustom();
        panelCustom3 = new Custom.PanelCustom();
        panelCustom4 = new Custom.PanelCustom();

        setBackground(new java.awt.Color(255, 254, 251));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lexend", 0, 30)); // NOI18N
        jLabel1.setText("Statistics Management");
        jLabel1.setPreferredSize(new java.awt.Dimension(342, 38));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 25, -1, -1));

        panelCustom1.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom1.setPreferredSize(new java.awt.Dimension(230, 230));
        panelCustom1.setRoundBottomLeft(30);
        panelCustom1.setRoundBottomRigt(30);
        panelCustom1.setRoundTopLeft(30);
        panelCustom1.setRoundTopRigt(30);

        jLabel2.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel2.setText("Sum of year ... : x.xxx.xxx.xxx VND");

        jLabel3.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel3.setText("Sum of year ... : x.xxx.xxx.xxx VND");

        jLabel4.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel4.setText("Sum of year ... : x.xxx.xxx.xxx VND");

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom1Layout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(24, 24, 24))
        );

        add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 103, 261, 612));

        panelCustom2.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom2.setPreferredSize(new java.awt.Dimension(685, 353));
        panelCustom2.setRoundBottomLeft(30);
        panelCustom2.setRoundBottomRigt(30);
        panelCustom2.setRoundTopLeft(30);
        panelCustom2.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        add(panelCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 362, 685, 353));

        panelCustom3.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom3.setPreferredSize(new java.awt.Dimension(426, 230));
        panelCustom3.setRoundBottomLeft(30);
        panelCustom3.setRoundBottomRigt(30);
        panelCustom3.setRoundTopLeft(30);
        panelCustom3.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom3Layout = new javax.swing.GroupLayout(panelCustom3);
        panelCustom3.setLayout(panelCustom3Layout);
        panelCustom3Layout.setHorizontalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        panelCustom3Layout.setVerticalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        add(panelCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 103, -1, -1));

        panelCustom4.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom4.setPreferredSize(new java.awt.Dimension(230, 230));
        panelCustom4.setRoundBottomLeft(30);
        panelCustom4.setRoundBottomRigt(30);
        panelCustom4.setRoundTopLeft(30);
        panelCustom4.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom4Layout = new javax.swing.GroupLayout(panelCustom4);
        panelCustom4.setLayout(panelCustom4Layout);
        panelCustom4Layout.setHorizontalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        panelCustom4Layout.setVerticalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        add(panelCustom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 103, 230, 230));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private Custom.PanelCustom panelCustom1;
    private Custom.PanelCustom panelCustom2;
    private Custom.PanelCustom panelCustom3;
    private Custom.PanelCustom panelCustom4;
    // End of variables declaration//GEN-END:variables
}
