/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

import javax.swing.JLabel;

/**
 *
 * @author quythuong
 */
public class panel_home extends javax.swing.JPanel {

	/**
	 * Creates new form panel_home
	 */
	public panel_home() {
		initComponents();
                String textWithLineBreak = "<html><body>Enjoy<br>your time<br>with our app</body></html>";
                jLabel2.setText(textWithLineBreak); 
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 254, 251));
        setPreferredSize(new java.awt.Dimension(1056, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lexend", 0, 30)); // NOI18N
        jLabel1.setText("Bookstore Management App");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 52, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lexend", 0, 58)); // NOI18N
        jLabel2.setText("Enjoy");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setName(""); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 177, -1, 340));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home - Bookimage550-550.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 99, -1, -1));

        jLabel4.setText("Application with useful features for bookstore management. This is the best app to use");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 700, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
