/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

/**
 *
 * @author Admin
 */
public class Panel_Receipt extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Receipt
     */
    public Panel_Receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        panelCustom1 = new Custom.PanelCustom();
        panelCustom3 = new Custom.PanelCustom();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelCustom2 = new Custom.PanelCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelCustom9 = new Custom.PanelCustom();
        panelCustom10 = new Custom.PanelCustom();
        lb_iconTrash = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonCustom1 = new Custom.ButtonCustom();
        buttonCustom2 = new Custom.ButtonCustom();
        panelCustom16 = new Custom.PanelCustom();
        jLabel10 = new javax.swing.JLabel();
        panelCustom17 = new Custom.PanelCustom();
        lb_iconTrash1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonCustom3 = new Custom.ButtonCustom();
        buttonCustom4 = new Custom.ButtonCustom();
        panelCustom18 = new Custom.PanelCustom();
        jLabel12 = new javax.swing.JLabel();
        panelCustom19 = new Custom.PanelCustom();
        lb_iconTrash2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonCustom5 = new Custom.ButtonCustom();
        buttonCustom6 = new Custom.ButtonCustom();
        panelCustom20 = new Custom.PanelCustom();
        jLabel14 = new javax.swing.JLabel();
        panelCustom23 = new Custom.PanelCustom();
        lb_iconTrash4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        buttonCustom9 = new Custom.ButtonCustom();
        buttonCustom10 = new Custom.ButtonCustom();
        panelCustom24 = new Custom.PanelCustom();
        jLabel18 = new javax.swing.JLabel();
        panelCustom11 = new Custom.PanelCustom();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        panelCustom12 = new Custom.PanelCustom();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        panelCustom13 = new Custom.PanelCustom();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        panelCustom14 = new Custom.PanelCustom();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        panelCustom15 = new Custom.PanelCustom();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        panelCustom4 = new Custom.PanelCustom();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lb_iconTrash5 = new javax.swing.JLabel();
        panelCustom5 = new Custom.PanelCustom();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        buttonCustom11 = new Custom.ButtonCustom();

        jPanel8.setBackground(new java.awt.Color(255, 254, 251));
        jPanel8.setPreferredSize(new java.awt.Dimension(1280, 740));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1398, 187, -1, -1));

        panelCustom3.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom3.setPreferredSize(new java.awt.Dimension(206, 299));
        panelCustom3.setRoundBottomLeft(30);
        panelCustom3.setRoundBottomRigt(30);
        panelCustom3.setRoundTopLeft(30);
        panelCustom3.setRoundTopRigt(30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("HÌNH ANH");

        jLabel6.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel6.setText("ThongTin");

        jLabel7.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel7.setText("Quantity:");

        jLabel8.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel8.setText("Price:");

        javax.swing.GroupLayout panelCustom3Layout = new javax.swing.GroupLayout(panelCustom3);
        panelCustom3.setLayout(panelCustom3Layout);
        panelCustom3Layout.setHorizontalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom3Layout.createSequentialGroup()
                .addGroup(panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6))
                    .addGroup(panelCustom3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom3Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelCustom3Layout.setVerticalGroup(
            panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(23, 23, 23))
        );

        jPanel8.add(panelCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 62, -1, -1));

        panelCustom2.setPreferredSize(new java.awt.Dimension(532, 87));
        panelCustom2.setRoundBottomLeft(30);
        panelCustom2.setRoundBottomRigt(30);
        panelCustom2.setRoundTopLeft(30);
        panelCustom2.setRoundTopRigt(30);

        jLabel1.setFont(new java.awt.Font("Lexend SemiBold", 0, 15)); // NOI18N
        jLabel1.setText("NEW ORDER");

        jLabel2.setFont(new java.awt.Font("Lexend Light", 0, 14)); // NOI18N
        jLabel2.setText("Thank you for order our books");

        jLabel3.setFont(new java.awt.Font("Lexend Light", 1, 15)); // NOI18N
        jLabel3.setText("Date of receipt");

        jLabel4.setFont(new java.awt.Font("Lexend Light", 1, 15)); // NOI18N
        jLabel4.setText("Receipt ID");

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(161, 161, 161))))
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel8.add(panelCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 37, -1, -1));

        panelCustom9.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom9.setPreferredSize(new java.awt.Dimension(532, 378));
        panelCustom9.setRoundBottomLeft(30);
        panelCustom9.setRoundBottomRigt(30);
        panelCustom9.setRoundTopLeft(30);
        panelCustom9.setRoundTopRigt(30);

        panelCustom10.setBackground(new java.awt.Color(238, 238, 238));
        panelCustom10.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom10.setRoundBottomLeft(30);
        panelCustom10.setRoundBottomRigt(30);
        panelCustom10.setRoundTopLeft(30);
        panelCustom10.setRoundTopRigt(30);

        jLabel9.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel9.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

        buttonCustom1.setText("-");
        buttonCustom1.setRadius(500);

        buttonCustom2.setText("+");
        buttonCustom2.setRadius(500);

        panelCustom16.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom16.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom16.setRoundBottomLeft(30);
        panelCustom16.setRoundBottomRigt(30);
        panelCustom16.setRoundTopLeft(30);
        panelCustom16.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom16Layout = new javax.swing.GroupLayout(panelCustom16);
        panelCustom16.setLayout(panelCustom16Layout);
        panelCustom16Layout.setHorizontalGroup(
            panelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        panelCustom16Layout.setVerticalGroup(
            panelCustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
        jLabel10.setText("xxx.xxx.xxx VNĐ");

        javax.swing.GroupLayout panelCustom10Layout = new javax.swing.GroupLayout(panelCustom10);
        panelCustom10.setLayout(panelCustom10Layout);
        panelCustom10Layout.setHorizontalGroup(
            panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_iconTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelCustom10Layout.setVerticalGroup(
            panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom10Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addComponent(lb_iconTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCustom16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        panelCustom17.setBackground(new java.awt.Color(238, 238, 238));
        panelCustom17.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom17.setRoundBottomLeft(30);
        panelCustom17.setRoundBottomRigt(30);
        panelCustom17.setRoundTopLeft(30);
        panelCustom17.setRoundTopRigt(30);

        jLabel11.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel11.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

        buttonCustom3.setText("-");
        buttonCustom3.setRadius(500);

        buttonCustom4.setText("+");
        buttonCustom4.setRadius(500);

        panelCustom18.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom18.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom18.setRoundBottomLeft(30);
        panelCustom18.setRoundBottomRigt(30);
        panelCustom18.setRoundTopLeft(30);
        panelCustom18.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom18Layout = new javax.swing.GroupLayout(panelCustom18);
        panelCustom18.setLayout(panelCustom18Layout);
        panelCustom18Layout.setHorizontalGroup(
            panelCustom18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        panelCustom18Layout.setVerticalGroup(
            panelCustom18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
        jLabel12.setText("xxx.xxx.xxx VND");

        javax.swing.GroupLayout panelCustom17Layout = new javax.swing.GroupLayout(panelCustom17);
        panelCustom17.setLayout(panelCustom17Layout);
        panelCustom17Layout.setHorizontalGroup(
            panelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom17Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_iconTrash1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelCustom17Layout.setVerticalGroup(
            panelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom17Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustom17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addComponent(lb_iconTrash1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCustom18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        panelCustom19.setBackground(new java.awt.Color(238, 238, 238));
        panelCustom19.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom19.setRoundBottomLeft(30);
        panelCustom19.setRoundBottomRigt(30);
        panelCustom19.setRoundTopLeft(30);
        panelCustom19.setRoundTopRigt(30);

        jLabel13.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel13.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

        buttonCustom5.setText("-");
        buttonCustom5.setRadius(500);

        buttonCustom6.setText("+");
        buttonCustom6.setRadius(500);

        panelCustom20.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom20.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom20.setRoundBottomLeft(30);
        panelCustom20.setRoundBottomRigt(30);
        panelCustom20.setRoundTopLeft(30);
        panelCustom20.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom20Layout = new javax.swing.GroupLayout(panelCustom20);
        panelCustom20.setLayout(panelCustom20Layout);
        panelCustom20Layout.setHorizontalGroup(
            panelCustom20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        panelCustom20Layout.setVerticalGroup(
            panelCustom20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
        jLabel14.setText("xxx.xxx.xxx VND");

        javax.swing.GroupLayout panelCustom19Layout = new javax.swing.GroupLayout(panelCustom19);
        panelCustom19.setLayout(panelCustom19Layout);
        panelCustom19Layout.setHorizontalGroup(
            panelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom19Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_iconTrash2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelCustom19Layout.setVerticalGroup(
            panelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom19Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustom19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addComponent(lb_iconTrash2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCustom20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        panelCustom23.setBackground(new java.awt.Color(238, 238, 238));
        panelCustom23.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom23.setRoundBottomLeft(30);
        panelCustom23.setRoundBottomRigt(30);
        panelCustom23.setRoundTopLeft(30);
        panelCustom23.setRoundTopRigt(30);

        jLabel17.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel17.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");

        buttonCustom9.setText("-");
        buttonCustom9.setRadius(500);

        buttonCustom10.setText("+");
        buttonCustom10.setRadius(500);

        panelCustom24.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom24.setPreferredSize(new java.awt.Dimension(519, 71));
        panelCustom24.setRoundBottomLeft(30);
        panelCustom24.setRoundBottomRigt(30);
        panelCustom24.setRoundTopLeft(30);
        panelCustom24.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom24Layout = new javax.swing.GroupLayout(panelCustom24);
        panelCustom24.setLayout(panelCustom24Layout);
        panelCustom24Layout.setHorizontalGroup(
            panelCustom24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );
        panelCustom24Layout.setVerticalGroup(
            panelCustom24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
        jLabel18.setText("xxx.xxx.xxx VND");

        javax.swing.GroupLayout panelCustom23Layout = new javax.swing.GroupLayout(panelCustom23);
        panelCustom23.setLayout(panelCustom23Layout);
        panelCustom23Layout.setHorizontalGroup(
            panelCustom23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom23Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_iconTrash4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelCustom23Layout.setVerticalGroup(
            panelCustom23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom23Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelCustom23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustom23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustom23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addComponent(lb_iconTrash4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCustom24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout panelCustom9Layout = new javax.swing.GroupLayout(panelCustom9);
        panelCustom9.setLayout(panelCustom9Layout);
        panelCustom9Layout.setHorizontalGroup(
            panelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom9Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(panelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustom10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCustom17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCustom19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCustom23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelCustom9Layout.setVerticalGroup(
            panelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCustom17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCustom23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustom19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel8.add(panelCustom9, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 130, -1, -1));

        panelCustom11.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom11.setPreferredSize(new java.awt.Dimension(206, 299));
        panelCustom11.setRoundBottomLeft(30);
        panelCustom11.setRoundBottomRigt(30);
        panelCustom11.setRoundTopLeft(30);
        panelCustom11.setRoundTopRigt(30);

        jLabel29.setBackground(new java.awt.Color(255, 255, 0));
        jLabel29.setText("HÌNH ANH");

        jLabel30.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel30.setText("ThongTin");

        jLabel31.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel31.setText("Quantity:");

        jLabel32.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel32.setText("Price:");

        javax.swing.GroupLayout panelCustom11Layout = new javax.swing.GroupLayout(panelCustom11);
        panelCustom11.setLayout(panelCustom11Layout);
        panelCustom11Layout.setHorizontalGroup(
            panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom11Layout.createSequentialGroup()
                .addGroup(panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom11Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel30))
                    .addGroup(panelCustom11Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom11Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelCustom11Layout.setVerticalGroup(
            panelCustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(23, 23, 23))
        );

        jPanel8.add(panelCustom11, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 62, -1, -1));

        panelCustom12.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom12.setPreferredSize(new java.awt.Dimension(206, 299));
        panelCustom12.setRoundBottomLeft(30);
        panelCustom12.setRoundBottomRigt(30);
        panelCustom12.setRoundTopLeft(30);
        panelCustom12.setRoundTopRigt(30);

        jLabel33.setBackground(new java.awt.Color(255, 255, 0));
        jLabel33.setText("HÌNH ANH");

        jLabel34.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel34.setText("ThongTin");

        jLabel35.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel35.setText("Quantity:");

        jLabel36.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel36.setText("Price:");

        javax.swing.GroupLayout panelCustom12Layout = new javax.swing.GroupLayout(panelCustom12);
        panelCustom12.setLayout(panelCustom12Layout);
        panelCustom12Layout.setHorizontalGroup(
            panelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom12Layout.createSequentialGroup()
                .addGroup(panelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom12Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel34))
                    .addGroup(panelCustom12Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom12Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelCustom12Layout.setVerticalGroup(
            panelCustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom12Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(23, 23, 23))
        );

        jPanel8.add(panelCustom12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 403, -1, -1));

        panelCustom13.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom13.setPreferredSize(new java.awt.Dimension(206, 299));
        panelCustom13.setRoundBottomLeft(30);
        panelCustom13.setRoundBottomRigt(30);
        panelCustom13.setRoundTopLeft(30);
        panelCustom13.setRoundTopRigt(30);

        jLabel37.setBackground(new java.awt.Color(255, 255, 0));
        jLabel37.setText("HÌNH ANH");

        jLabel38.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel38.setText("ThongTin");

        jLabel39.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel39.setText("Quantity:");

        jLabel40.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel40.setText("Price:");

        javax.swing.GroupLayout panelCustom13Layout = new javax.swing.GroupLayout(panelCustom13);
        panelCustom13.setLayout(panelCustom13Layout);
        panelCustom13Layout.setHorizontalGroup(
            panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom13Layout.createSequentialGroup()
                .addGroup(panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom13Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel38))
                    .addGroup(panelCustom13Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom13Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelCustom13Layout.setVerticalGroup(
            panelCustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom13Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addGap(23, 23, 23))
        );

        jPanel8.add(panelCustom13, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 62, -1, -1));

        panelCustom14.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom14.setPreferredSize(new java.awt.Dimension(206, 299));
        panelCustom14.setRoundBottomLeft(30);
        panelCustom14.setRoundBottomRigt(30);
        panelCustom14.setRoundTopLeft(30);
        panelCustom14.setRoundTopRigt(30);

        jLabel41.setBackground(new java.awt.Color(255, 255, 0));
        jLabel41.setText("HÌNH ANH");

        jLabel42.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel42.setText("ThongTin");

        jLabel43.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel43.setText("Quantity:");

        jLabel44.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel44.setText("Price:");

        javax.swing.GroupLayout panelCustom14Layout = new javax.swing.GroupLayout(panelCustom14);
        panelCustom14.setLayout(panelCustom14Layout);
        panelCustom14Layout.setHorizontalGroup(
            panelCustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom14Layout.createSequentialGroup()
                .addGroup(panelCustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom14Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel42))
                    .addGroup(panelCustom14Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom14Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelCustom14Layout.setVerticalGroup(
            panelCustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom14Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addGap(23, 23, 23))
        );

        jPanel8.add(panelCustom14, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 403, -1, -1));

        panelCustom15.setBackground(new java.awt.Color(243, 243, 243));
        panelCustom15.setPreferredSize(new java.awt.Dimension(206, 299));
        panelCustom15.setRoundBottomLeft(30);
        panelCustom15.setRoundBottomRigt(30);
        panelCustom15.setRoundTopLeft(30);
        panelCustom15.setRoundTopRigt(30);

        jLabel45.setBackground(new java.awt.Color(255, 255, 0));
        jLabel45.setText("HÌNH ANH");

        jLabel46.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel46.setText("ThongTin");

        jLabel47.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel47.setText("Quantity:");

        jLabel48.setFont(new java.awt.Font("Lexend Light", 0, 15)); // NOI18N
        jLabel48.setText("Price:");

        javax.swing.GroupLayout panelCustom15Layout = new javax.swing.GroupLayout(panelCustom15);
        panelCustom15.setLayout(panelCustom15Layout);
        panelCustom15Layout.setHorizontalGroup(
            panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom15Layout.createSequentialGroup()
                .addGroup(panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom15Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel46))
                    .addGroup(panelCustom15Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom15Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelCustom15Layout.setVerticalGroup(
            panelCustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom15Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addGap(23, 23, 23))
        );

        jPanel8.add(panelCustom15, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 403, -1, -1));

        panelCustom4.setPreferredSize(new java.awt.Dimension(532, 183));
        panelCustom4.setRoundBottomLeft(30);
        panelCustom4.setRoundBottomRigt(30);
        panelCustom4.setRoundTopLeft(30);
        panelCustom4.setRoundTopRigt(30);

        jLabel19.setFont(new java.awt.Font("Lexend Medium", 0, 14)); // NOI18N
        jLabel19.setText("Received :");

        jLabel20.setFont(new java.awt.Font("Lexend Medium", 0, 14)); // NOI18N
        jLabel20.setText("Subtotal :");

        jLabel21.setFont(new java.awt.Font("Lexend Medium", 0, 14)); // NOI18N
        jLabel21.setText("Changed :");

        jLabel22.setFont(new java.awt.Font("Lexend SemiBold", 0, 20)); // NOI18N
        jLabel22.setText("Total :");

        jLabel23.setFont(new java.awt.Font("Lexend Medium", 0, 14)); // NOI18N
        jLabel23.setText("Sale :");

        panelCustom5.setBackground(new java.awt.Color(238, 238, 238));
        panelCustom5.setForeground(new java.awt.Color(217, 217, 217));
        panelCustom5.setRoundBottomLeft(30);
        panelCustom5.setRoundBottomRigt(30);
        panelCustom5.setRoundTopLeft(30);
        panelCustom5.setRoundTopRigt(30);

        javax.swing.GroupLayout panelCustom5Layout = new javax.swing.GroupLayout(panelCustom5);
        panelCustom5.setLayout(panelCustom5Layout);
        panelCustom5Layout.setHorizontalGroup(
            panelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        panelCustom5Layout.setVerticalGroup(
            panelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jLabel24.setFont(new java.awt.Font("Lexend Light", 0, 14)); // NOI18N
        jLabel24.setText("xxx.xxx.xxx.xxx.xxx VND");

        jLabel25.setFont(new java.awt.Font("Lexend Light", 0, 14)); // NOI18N
        jLabel25.setText("xxx.xxx.xxx.xxx.xxx VND");

        jLabel26.setFont(new java.awt.Font("Lexend Light", 0, 14)); // NOI18N
        jLabel26.setText("10%");

        jLabel27.setText("__________________________________________________");

        jLabel28.setFont(new java.awt.Font("Lexend Light", 0, 14)); // NOI18N
        jLabel28.setText("xxx.xxx.xxx.xxx.xxx VND");

        buttonCustom11.setBackground(new java.awt.Color(255, 216, 156));
        buttonCustom11.setText("Export Receipt");
        buttonCustom11.setFont(new java.awt.Font("Lexend Light", 0, 16)); // NOI18N
        buttonCustom11.setRadius(25);
        buttonCustom11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustom11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCustom4Layout = new javax.swing.GroupLayout(panelCustom4);
        panelCustom4.setLayout(panelCustom4Layout);
        panelCustom4Layout.setHorizontalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom4Layout.createSequentialGroup()
                .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustom4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(1, 1, 1))
                    .addGroup(panelCustom4Layout.createSequentialGroup()
                        .addGap(0, 274, Short.MAX_VALUE)
                        .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(panelCustom4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCustom4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lb_iconTrash5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        panelCustom4Layout.setVerticalGroup(
            panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel25)))
                .addGap(24, 24, 24)
                .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel28))
                .addGap(13, 13, 13)
                .addGroup(panelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_iconTrash5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel8.add(panelCustom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 515, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustom11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustom11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustom11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.ButtonCustom buttonCustom1;
    private Custom.ButtonCustom buttonCustom10;
    private Custom.ButtonCustom buttonCustom11;
    private Custom.ButtonCustom buttonCustom2;
    private Custom.ButtonCustom buttonCustom3;
    private Custom.ButtonCustom buttonCustom4;
    private Custom.ButtonCustom buttonCustom5;
    private Custom.ButtonCustom buttonCustom6;
    private Custom.ButtonCustom buttonCustom9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lb_iconTrash;
    private javax.swing.JLabel lb_iconTrash1;
    private javax.swing.JLabel lb_iconTrash2;
    private javax.swing.JLabel lb_iconTrash4;
    private javax.swing.JLabel lb_iconTrash5;
    private Custom.PanelCustom panelCustom1;
    private Custom.PanelCustom panelCustom10;
    private Custom.PanelCustom panelCustom11;
    private Custom.PanelCustom panelCustom12;
    private Custom.PanelCustom panelCustom13;
    private Custom.PanelCustom panelCustom14;
    private Custom.PanelCustom panelCustom15;
    private Custom.PanelCustom panelCustom16;
    private Custom.PanelCustom panelCustom17;
    private Custom.PanelCustom panelCustom18;
    private Custom.PanelCustom panelCustom19;
    private Custom.PanelCustom panelCustom2;
    private Custom.PanelCustom panelCustom20;
    private Custom.PanelCustom panelCustom23;
    private Custom.PanelCustom panelCustom24;
    private Custom.PanelCustom panelCustom3;
    private Custom.PanelCustom panelCustom4;
    private Custom.PanelCustom panelCustom5;
    private Custom.PanelCustom panelCustom9;
    // End of variables declaration//GEN-END:variables
}
