/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

import com.nhom08.bookstore.DAO.IReceiptDAO;
import com.nhom08.bookstore.Models.IReceiptModel;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lombok.Getter;
import lombok.Setter;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author quythuong
 */
@Getter
@Setter
public class panel_iReceipt extends javax.swing.JPanel {

	/**
	 * Creates new form panel_iRecept
	 */
	private String iReceiptId;
	private IReceiptDAO iReceiptDAO = new IReceiptDAO();
	private DefaultTableModel tableModel;
	SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
	public panel_iReceipt() {
		initComponents();
		loadTable();
	}
	public void loadTable() {
		List<IReceiptModel> iReceiptList = iReceiptDAO.getAll();
		tableModel = (DefaultTableModel)table_iReceiptList.getModel();
		//clear the table
		tableModel.setRowCount(0);
		// load the table
		iReceiptList.forEach((e)->{
			tableModel.addRow(new Object[] {e.getId(), e.getPublisherId(), formatter.format(e.getDate())});
		});
	}
	public void clearText() {
		this.tf_publisherId.setText("");
		this.tf_iReceiptId.setText("");
		this.tf_date.setText("");
	}
	public void disableText() {
		tf_date.setEditable(true);
		tf_iReceiptId.setEditable(true);
		tf_publisherId.setEditable(true);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel2 = new javax.swing.JLabel();
                panelCustom2 = new Custom.PanelCustom();
                btn_add = new Custom.ButtonCustom();
                btn_edit = new Custom.ButtonCustom();
                btn_delete = new Custom.ButtonCustom();
                panel_forTable = new Custom.PanelCustom();
                jScrollPane1 = new javax.swing.JScrollPane();
                table_iReceiptList = new javax.swing.JTable();
                panel_forInfo = new Custom.PanelCustom();
                jPanel1 = new javax.swing.JPanel();
                tf_iReceiptId = new com.nhom08.bookstore.GUI.TextFieldCustom();
                jLabel4 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                tf_publisherId = new com.nhom08.bookstore.GUI.TextFieldCustom();
                jLabel5 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                tf_date = new com.nhom08.bookstore.GUI.TextFieldCustom();
                jLabel6 = new javax.swing.JLabel();
                lbl_saveBtn = new javax.swing.JLabel();
                lbl_clearBtn = new javax.swing.JLabel();
                panel_goToIReceiptDetails = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 254, 251));
                setPreferredSize(new java.awt.Dimension(1056, 740));
                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setFont(new java.awt.Font("Lexend", 0, 30)); // NOI18N
                jLabel2.setText("I-Receipts Management");
                add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 25, -1, -1));

                panelCustom2.setPreferredSize(new java.awt.Dimension(695, 68));
                panelCustom2.setRoundBottomLeft(10);
                panelCustom2.setRoundBottomRigt(10);
                panelCustom2.setRoundTopLeft(10);
                panelCustom2.setRoundTopRigt(10);
                panelCustom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                btn_add.setBackground(new java.awt.Color(217, 217, 217));
                btn_add.setBorder(null);
                btn_add.setText("Add");
                btn_add.setBorderColor(new java.awt.Color(217, 217, 217));
                btn_add.setColor(new java.awt.Color(217, 217, 217));
                btn_add.setColorOver(new java.awt.Color(217, 217, 217));
                btn_add.setFont(new java.awt.Font("Lexend", 0, 24)); // NOI18N
                btn_add.setPreferredSize(new java.awt.Dimension(160, 42));
                btn_add.setRadius(20);
                btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_addMouseClicked(evt);
                        }
                });
                btn_add.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_addActionPerformed(evt);
                        }
                });
                panelCustom2.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));

                btn_edit.setBackground(new java.awt.Color(217, 217, 217));
                btn_edit.setBorder(null);
                btn_edit.setText("Edit");
                btn_edit.setBorderColor(new java.awt.Color(217, 217, 217));
                btn_edit.setColor(new java.awt.Color(217, 217, 217));
                btn_edit.setColorOver(new java.awt.Color(217, 217, 217));
                btn_edit.setFont(new java.awt.Font("Lexend", 0, 24)); // NOI18N
                btn_edit.setPreferredSize(new java.awt.Dimension(160, 42));
                btn_edit.setRadius(20);
                btn_edit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_editActionPerformed(evt);
                        }
                });
                panelCustom2.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 14, -1, -1));

                btn_delete.setBackground(new java.awt.Color(217, 217, 217));
                btn_delete.setBorder(null);
                btn_delete.setText("Delete");
                btn_delete.setBorderColor(new java.awt.Color(217, 217, 217));
                btn_delete.setColor(new java.awt.Color(217, 217, 217));
                btn_delete.setColorOver(new java.awt.Color(217, 217, 217));
                btn_delete.setFont(new java.awt.Font("Lexend", 0, 24)); // NOI18N
                btn_delete.setPreferredSize(new java.awt.Dimension(160, 42));
                btn_delete.setRadius(20);
                btn_delete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_deleteActionPerformed(evt);
                        }
                });
                panelCustom2.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 14, -1, -1));

                add(panelCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 103, -1, -1));

                panel_forTable.setPreferredSize(new java.awt.Dimension(695, 515));
                panel_forTable.setRoundBottomLeft(10);
                panel_forTable.setRoundBottomRigt(10);
                panel_forTable.setRoundTopLeft(10);
                panel_forTable.setRoundTopRigt(10);

                table_iReceiptList.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                table_iReceiptList.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Mã phiếu nhập", "Mã NXB", "Ngày nhập"
                        }
                ));
                table_iReceiptList.setRowHeight(32);
                table_iReceiptList.getTableHeader().setResizingAllowed(false);
                table_iReceiptList.getTableHeader().setReorderingAllowed(false);
                table_iReceiptList.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                table_iReceiptListMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(table_iReceiptList);

                javax.swing.GroupLayout panel_forTableLayout = new javax.swing.GroupLayout(panel_forTable);
                panel_forTable.setLayout(panel_forTableLayout);
                panel_forTableLayout.setHorizontalGroup(
                        panel_forTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_forTableLayout.createSequentialGroup()
                                .addContainerGap(21, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                );
                panel_forTableLayout.setVerticalGroup(
                        panel_forTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_forTableLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
                );

                add(panel_forTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 200, -1, -1));

                panel_forInfo.setPreferredSize(new java.awt.Dimension(248, 612));
                panel_forInfo.setRoundBottomLeft(10);
                panel_forInfo.setRoundBottomRigt(10);
                panel_forInfo.setRoundTopLeft(10);
                panel_forInfo.setRoundTopRigt(10);
                panel_forInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tf_iReceiptId.setEditable(false);
                tf_iReceiptId.setBackground(new java.awt.Color(204, 204, 204));
                tf_iReceiptId.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                tf_iReceiptId.setPreferredSize(new java.awt.Dimension(210, 33));
                tf_iReceiptId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tf_iReceiptIdActionPerformed(evt);
                        }
                });
                jPanel1.add(tf_iReceiptId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 40));

                jLabel4.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
                jLabel4.setText("Mã phiếu nhập");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                panel_forInfo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

                jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tf_publisherId.setEditable(false);
                tf_publisherId.setBackground(new java.awt.Color(204, 204, 204));
                tf_publisherId.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                tf_publisherId.setPreferredSize(new java.awt.Dimension(210, 33));
                tf_publisherId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tf_publisherIdActionPerformed(evt);
                        }
                });
                jPanel3.add(tf_publisherId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 40));

                jLabel5.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
                jLabel5.setText("Mã nhà xuất bản");
                jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                panel_forInfo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

                jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tf_date.setEditable(false);
                tf_date.setBackground(new java.awt.Color(204, 204, 204));
                tf_date.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                tf_date.setPreferredSize(new java.awt.Dimension(210, 33));
                tf_date.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tf_dateActionPerformed(evt);
                        }
                });
                jPanel4.add(tf_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 40));

                jLabel6.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
                jLabel6.setText("Ngày nhập");
                jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                panel_forInfo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

                lbl_saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
                lbl_saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbl_saveBtnMouseClicked(evt);
                        }
                });
                panel_forInfo.add(lbl_saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 556, 40, 38));

                lbl_clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancle.png"))); // NOI18N
                lbl_clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lbl_clearBtnMouseClicked(evt);
                        }
                });
                panel_forInfo.add(lbl_clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 556, 40, 38));

                add(panel_forInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 103, -1, -1));

                panel_goToIReceiptDetails.setBackground(new java.awt.Color(255, 254, 251));

                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-small-right.png"))); // NOI18N

                javax.swing.GroupLayout panel_goToIReceiptDetailsLayout = new javax.swing.GroupLayout(panel_goToIReceiptDetails);
                panel_goToIReceiptDetails.setLayout(panel_goToIReceiptDetailsLayout);
                panel_goToIReceiptDetailsLayout.setHorizontalGroup(
                        panel_goToIReceiptDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(panel_goToIReceiptDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_goToIReceiptDetailsLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
                panel_goToIReceiptDetailsLayout.setVerticalGroup(
                        panel_goToIReceiptDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addGroup(panel_goToIReceiptDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_goToIReceiptDetailsLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );

                add(panel_goToIReceiptDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 25, 40, 38));
        }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tf_iReceiptIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_iReceiptIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_iReceiptIdActionPerformed

    private void tf_publisherIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_publisherIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_publisherIdActionPerformed

    private void tf_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dateActionPerformed

        private void table_iReceiptListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_iReceiptListMouseClicked
                // TODO add your handling code here:
		tf_date.setBackground(new Color(204, 204, 204));
		tf_iReceiptId.setBackground(new Color(204, 204, 204));
		tf_publisherId.setBackground(new Color(204, 204, 204));
        }//GEN-LAST:event_table_iReceiptListMouseClicked

        private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
                // TODO add your handling code here:
		tf_date.setBackground(Color.WHITE);
		tf_iReceiptId.setBackground(Color.WHITE);
		tf_publisherId.setBackground(Color.WHITE);
		
		
		disableText();
		
		iReceiptId = null;
		
		this.clearText();
        }//GEN-LAST:event_btn_addMouseClicked

        private void lbl_clearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clearBtnMouseClicked
                // TODO add your handling code here:
		clearText();
		this.iReceiptId = null;
		this.table_iReceiptList.clearSelection();
        }//GEN-LAST:event_lbl_clearBtnMouseClicked

        private void lbl_saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_saveBtnMouseClicked
                // TODO add your handling code here:
		if(!tf_iReceiptId.isEditable()) {
			JOptionPane.showMessageDialog(this, "Chưa chọn thêm hoặc chỉnh sửa!");
			return;
		}
		if(tf_iReceiptId.getText().isEmpty() || tf_publisherId.getText().isEmpty() || tf_date.getText().isEmpty()) {
			JOptionPane.showMessageDialog(this, "Không được để trống các trường!");
			return;
		}
		
		try {
			IReceiptModel iReceipt = new IReceiptModel(tf_iReceiptId.getText(), tf_publisherId.getText(), new java.sql.Date(formatter.parse(tf_date.getText()).getTime()));
			System.out.println(iReceipt.toString());
			//save to DB
			iReceiptDAO.save(iReceipt);
		} catch (ParseException | SQLException ex) {
			Logger.getLogger(panel_iReceipt.class.getName()).log(Level.SEVERE, null, ex);			JOptionPane.showMessageDialog(this, "Lưu phiếu nhập thất bại");

		}
		JOptionPane.showMessageDialog(this, "Lưu phiếu nhập thành công");
		loadTable();
		clearText();
		disableText();
        }//GEN-LAST:event_lbl_saveBtnMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private Custom.ButtonCustom btn_add;
        private Custom.ButtonCustom btn_delete;
        private Custom.ButtonCustom btn_edit;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lbl_clearBtn;
        private javax.swing.JLabel lbl_saveBtn;
        private Custom.PanelCustom panelCustom2;
        private Custom.PanelCustom panel_forInfo;
        private Custom.PanelCustom panel_forTable;
        private javax.swing.JPanel panel_goToIReceiptDetails;
        private javax.swing.JTable table_iReceiptList;
        private com.nhom08.bookstore.GUI.TextFieldCustom tf_date;
        private com.nhom08.bookstore.GUI.TextFieldCustom tf_iReceiptId;
        private com.nhom08.bookstore.GUI.TextFieldCustom tf_publisherId;
        // End of variables declaration//GEN-END:variables
}
