/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

import javax.swing.text.View.*;

/**
 *
 * @author Admin
 */
public class Panel_BookItem extends javax.swing.JPanel {

    /**
     * Creates new form Panel_BookItem
     */
    public Panel_BookItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel37 = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_quantity = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 243, 243));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(255, 255, 0));
        jLabel37.setText("HÌNH ANH");
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lbl_bookName.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        lbl_bookName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bookName.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");
        add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 177, 175, 60));

        lbl_quantity.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        lbl_quantity.setText("xx xxx");
        add(lbl_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 248, -1, -1));

        lbl_price.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        lbl_price.setText("xxx.xxx.xxx VND");
        add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 270, -1, -1));

        jLabel41.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel41.setText("Quantity:");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 248, -1, -1));

        jLabel42.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel42.setText("Price:");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_quantity;
    // End of variables declaration//GEN-END:variables
}
