/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

import com.nhom08.bookstore.DAO.DBConnection;
import com.nhom08.bookstore.DAO.EmployeeDAO;
import com.nhom08.bookstore.ManagerFrame;
import com.nhom08.bookstore.Models.EmployeeModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quythuong
 */
public class panel_employees extends javax.swing.JPanel {

    /**
     * Creates new form panel_employees
     */
    public panel_employees() {
        initComponents();
//        this.cardPanel = cardPanel;
//        cardLayout = (CardLayout) cardPanel.getLayout();
        // Khởi tạo kết nối CSDL từ DBConnection
        Connection con = (new DBConnection()).GetDBConnection();

        // Khởi tạo đối tượng EmployeeDAO với kết nối CSDL đã tạo
        employeeDAO = new EmployeeDAO();

        try {
            // Hiển thị dữ liệu nhân viên
            displayEmployeeData();
            reset();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void reset() {
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_add.setEnabled(true);
        txt_maNV.setEnabled(true);
        txt_tenNV.setEnabled(true);
        txt_diaChi.setEnabled(true);
        txt_tenTaiKhoan.setEnabled(true);
        txt_matKhau.setEnabled(true);
        txt_maNV.setText("");
        txt_tenNV.setText("");
        cb_gioiTinh.setSelectedIndex(0); // Chọn giá trị mặc định hoặc giá trị mong muốn khác
        txt_diaChi.setText("");
        cb_cap.setSelectedIndex(0); // Chọn giá trị mặc định hoặc giá trị mong muốn khác
        txt_tenTaiKhoan.setText("");
        // Mở và xóa các text field khác ở đây tương tự
    }

    private EmployeeDAO employeeDAO;

    public panel_employees(JPanel cardPanel) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void displayEmployeeData() throws SQLException {
        List<EmployeeModel> employees = employeeDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng
        for (EmployeeModel employee : employees) {
            model.addRow(new Object[]{
                employee.getId(),
                employee.getName(),
                employee.getSex(),
                employee.getAddress(),
                employee.getLevel(),
                employee.getPosition(),
                employee.getAccount()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrow = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCustom1 = new Custom.PanelCustom();
        btn_add = new Custom.ButtonCustom();
        btn_edit = new Custom.ButtonCustom();
        btn_delete = new Custom.ButtonCustom();
        panelCustom2 = new Custom.PanelCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelCustom3 = new Custom.PanelCustom();
        jPanel1 = new javax.swing.JPanel();
        txt_maNV = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_tenNV = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cb_gioiTinh = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txt_diaChi = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cb_cap = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        txt_matKhau = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txt_tenTaiKhoan = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel13 = new javax.swing.JLabel();
        btn_huy = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1056, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-small-right.png"))); // NOI18N
        arrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowMouseClicked(evt);
            }
        });
        add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lexend", 0, 30)); // NOI18N
        jLabel2.setText("Employees Management");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 25, -1, -1));

        panelCustom1.setPreferredSize(new java.awt.Dimension(695, 68));
        panelCustom1.setRoundBottomLeft(10);
        panelCustom1.setRoundBottomRigt(10);
        panelCustom1.setRoundTopLeft(10);
        panelCustom1.setRoundTopRigt(10);
        panelCustom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_add.setBackground(new java.awt.Color(217, 217, 217));
        btn_add.setBorder(null);
        btn_add.setText("Add");
        btn_add.setBorderColor(new java.awt.Color(217, 217, 217));
        btn_add.setFont(new java.awt.Font("Lexend", 0, 24)); // NOI18N
        btn_add.setPreferredSize(new java.awt.Dimension(160, 42));
        btn_add.setRadius(20);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        panelCustom1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));
        btn_add.getAccessibleContext().setAccessibleDescription("");

        btn_edit.setBackground(new java.awt.Color(217, 217, 217));
        btn_edit.setBorder(null);
        btn_edit.setText("Edit");
        btn_edit.setBorderColor(new java.awt.Color(217, 217, 217));
        btn_edit.setFont(new java.awt.Font("Lexend", 0, 24)); // NOI18N
        btn_edit.setPreferredSize(new java.awt.Dimension(160, 42));
        btn_edit.setRadius(20);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        panelCustom1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 14, -1, -1));

        btn_delete.setBackground(new java.awt.Color(217, 217, 217));
        btn_delete.setBorder(null);
        btn_delete.setText("Delete");
        btn_delete.setBorderColor(new java.awt.Color(217, 217, 217));
        btn_delete.setFont(new java.awt.Font("Lexend", 0, 24)); // NOI18N
        btn_delete.setPreferredSize(new java.awt.Dimension(160, 42));
        btn_delete.setRadius(20);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        panelCustom1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 14, -1, -1));

        add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 103, -1, -1));

        panelCustom2.setPreferredSize(new java.awt.Dimension(695, 515));
        panelCustom2.setRoundBottomLeft(10);
        panelCustom2.setRoundBottomRigt(10);
        panelCustom2.setRoundTopLeft(10);
        panelCustom2.setRoundTopRigt(10);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(jTable1.getFont().deriveFont((float)12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên", "Giới tính", "Địa chỉ", "Cấp", "Chức vụ", "Tên Tài Khoản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        add(panelCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 200, -1, -1));

        panelCustom3.setPreferredSize(new java.awt.Dimension(248, 612));
        panelCustom3.setRoundBottomLeft(10);
        panelCustom3.setRoundBottomRigt(10);
        panelCustom3.setRoundTopLeft(10);
        panelCustom3.setRoundTopRigt(10);
        panelCustom3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_maNV.setAutoscrolls(false);
        txt_maNV.setEnabled(false);
        txt_maNV.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_maNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNVActionPerformed(evt);
            }
        });
        jPanel1.add(txt_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel4.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel4.setText("Mã NV");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tenNV.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_tenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenNVActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel5.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel5.setText("Tên");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel6.setText("Giới tính");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cb_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Không xác định" }));
        jPanel4.add(cb_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 40));

        panelCustom3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 70));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_diaChi.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_diaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diaChiActionPerformed(evt);
            }
        });
        jPanel5.add(txt_diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel7.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel7.setText("Địa chỉ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 70));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel8.setText("Cấp");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cb_cap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel6.add(cb_cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 40));

        panelCustom3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 70));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_matKhau.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauActionPerformed(evt);
            }
        });
        jPanel8.add(txt_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel10.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel10.setText("Mật khẩu");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 70));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tenTaiKhoan.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_tenTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenTaiKhoanActionPerformed(evt);
            }
        });
        jPanel9.add(txt_tenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));
        txt_tenTaiKhoan.getAccessibleContext().setAccessibleName("Tên Tài Khoản");

        jLabel13.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel13.setText("Tên tài khoản");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 70));

        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancle.png"))); // NOI18N
        btn_huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_huyMouseClicked(evt);
            }
        });
        panelCustom3.add(btn_huy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, 38));
        btn_huy.getAccessibleContext().setAccessibleName("Cancel");

        add(panelCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 103, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // Lấy thông tin từ các trường nhập liệu
        int id = Integer.parseInt(txt_maNV.getText());
        String name = txt_tenNV.getText();
        String sex = (String) cb_gioiTinh.getSelectedItem();
        String address = txt_diaChi.getText();
        int level = Integer.parseInt((String) cb_cap.getSelectedItem());
        String account = txt_tenTaiKhoan.getText();
        String pass = txt_matKhau.getText();
        String position = "";

        // Tạo đối tượng EmployeeModel từ thông tin đã nhập
        EmployeeModel newEmployee = new EmployeeModel(id, name, sex, address, account, pass, level, position);

        try {
            // Gọi phương thức addEmployee của EmployeeDAO để thêm nhân viên mới vào CSDL
            employeeDAO.addEmployee(newEmployee);

            // Hiển thị lại dữ liệu trong bảng sau khi thêm nhân viên thành công
            displayEmployeeData();
            reset();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // Lấy thông tin từ các trường nhập liệu
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            // Không có hàng nào được chọn
            return;
        }

        int id = Integer.parseInt(txt_maNV.getText());
        String name = txt_tenNV.getText();
        String sex = (String) cb_gioiTinh.getSelectedItem();
        String address = txt_diaChi.getText();
        int level = Integer.parseInt((String) cb_cap.getSelectedItem());
        String account = txt_tenTaiKhoan.getText();
        String pass = txt_matKhau.getText();
        String position = "";

        // Tạo đối tượng EmployeeModel từ thông tin đã nhập
        EmployeeModel updatedEmployee = new EmployeeModel(id, name, sex, address, account, pass, level, position);
        try {
            // Gọi phương thức updateEmployee của EmployeeDAO để cập nhật thông tin nhân viên
            employeeDAO.updateEmployee(updatedEmployee);
            // Hiển thị lại dữ liệu trong bảng sau khi cập nhật thành công
            displayEmployeeData();
            reset();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // Lấy thông tin từ các trường nhập liệu
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            // Không có hàng nào được chọn
            return;
        }

        // Lấy mã nhân viên từ bảng
        String idAsString = jTable1.getValueAt(selectedRow, 0).toString();
        int id = Integer.parseInt(idAsString); // Chuyển đổi chuỗi thành số nguyên

        try {
            // Gọi phương thức deleteEmployee của EmployeeDAO để xóa nhân viên
            employeeDAO.deleteEmployee(id);
            // Hiển thị lại dữ liệu trong bảng sau khi xóa thành công
            displayEmployeeData();
            reset();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_maNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNVActionPerformed

    private void txt_tenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenNVActionPerformed

    private void txt_diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaChiActionPerformed

    private void txt_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauActionPerformed

    private void txt_tenTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenTaiKhoanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            btn_edit.setEnabled(true);
            btn_delete.setEnabled(true);
            
            // Lấy thông tin từ dòng được chọn và hiển thị lên các ô nhập liệu
            txt_maNV.setText(jTable1.getValueAt(selectedRow, 0).toString());
            txt_tenNV.setText(jTable1.getValueAt(selectedRow, 1).toString());
            cb_gioiTinh.setSelectedItem(jTable1.getValueAt(selectedRow, 2).toString());
            txt_diaChi.setText(jTable1.getValueAt(selectedRow, 3).toString());
            cb_cap.setSelectedItem(jTable1.getValueAt(selectedRow, 4).toString());
            txt_tenTaiKhoan.setText(jTable1.getValueAt(selectedRow, 6).toString());

            // Khóa trường mã nhân viên
            txt_maNV.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void arrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowMouseClicked
        // Lấy ra cửa sổ gốc chứa panel_employees
        ManagerFrame managerFrame = (ManagerFrame) SwingUtilities.getWindowAncestor(this);

        // Tạo một instance mới của panel_shifts
        panel_shifts panelShifts = new panel_shifts();

        // Thêm panel_shift vào TabbedPane thông qua phương thức của lớp cha
        managerFrame.addTabToPane("Shift", panelShifts);

        // Chuyển sang tab mới được thêm vào
        managerFrame.TabbedPane.setSelectedComponent(panelShifts);
    }//GEN-LAST:event_arrowMouseClicked

    private void btn_huyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huyMouseClicked
        // TODO add your handling code here:
        // Xóa nội dung của các trường nhập liệu
        reset();
    }//GEN-LAST:event_btn_huyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow;
    private Custom.ButtonCustom btn_add;
    private Custom.ButtonCustom btn_delete;
    private Custom.ButtonCustom btn_edit;
    private javax.swing.JLabel btn_huy;
    private javax.swing.JComboBox<String> cb_cap;
    private javax.swing.JComboBox<String> cb_gioiTinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private Custom.PanelCustom panelCustom1;
    private Custom.PanelCustom panelCustom2;
    private Custom.PanelCustom panelCustom3;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_diaChi;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_maNV;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_matKhau;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_tenNV;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_tenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
