/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

import com.nhom08.bookstore.DAO.BookDAO;
import com.nhom08.bookstore.DAO.IReceiptDetailsDAO;
import com.nhom08.bookstore.Models.BookModel;
import com.nhom08.bookstore.Models.IReceiptDetailsModel;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Admin
 */
@Getter
@Setter
public class panel_iReceiptDetail extends javax.swing.JPanel {

    /**
     * Creates new form panel_iReceiptDetail
     */
	private String iReceiptId;
	private IReceiptDetailsDAO iReceiptDAO = new IReceiptDetailsDAO();
	private BookDAO bookDAO = new BookDAO();
	private DefaultTableModel tableModel;
    public panel_iReceiptDetail() {
        initComponents();
	
	
    }
    public void loadTable() {
	    tableModel = (DefaultTableModel)table_iReceiptDetails.getModel();
	List<IReceiptDetailsModel> iReceiptDetailsList = iReceiptDAO.getAllByReceiptId(iReceiptId);
	
	iReceiptDetailsList.forEach((e)-> {
		BookModel book;
		    try {
			    book = bookDAO.getOne(e.getBookId());
			    tableModel.addRow(new Object[] {e.getIReceipId(), e.getBookId(), book.getName(), String.valueOf(e.getQuantity())});
		    } catch (SQLException ex) {
			    Logger.getLogger(panel_iReceiptDetail.class.getName()).log(Level.SEVERE, null, ex);
		    }
	});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel2 = new javax.swing.JLabel();
                panelCustom3 = new Custom.PanelCustom();
                jScrollPane1 = new javax.swing.JScrollPane();
                table_iReceiptDetails = new javax.swing.JTable();
                panelCustom4 = new Custom.PanelCustom();
                jPanel1 = new javax.swing.JPanel();
                tf_iReceiptId = new com.nhom08.bookstore.GUI.TextFieldCustom();
                jLabel4 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                tf_bookId = new com.nhom08.bookstore.GUI.TextFieldCustom();
                jLabel5 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                tf_bookName = new com.nhom08.bookstore.GUI.TextFieldCustom();
                jLabel6 = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                tf_quantity = new com.nhom08.bookstore.GUI.TextFieldCustom();
                jLabel7 = new javax.swing.JLabel();
                lbl_backBtn = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 254, 251));
                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setFont(new java.awt.Font("Lexend", 0, 30)); // NOI18N
                jLabel2.setText("I-Receipts Detail Management");
                add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 25, -1, -1));

                panelCustom3.setPreferredSize(new java.awt.Dimension(695, 515));
                panelCustom3.setRoundBottomLeft(10);
                panelCustom3.setRoundBottomRigt(10);
                panelCustom3.setRoundTopLeft(10);
                panelCustom3.setRoundTopRigt(10);

                table_iReceiptDetails.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                table_iReceiptDetails.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Mã phiếu nhập", "Mã sách", "Tên sách", "Số lượng nhập"
                        }
                ));
                table_iReceiptDetails.setRowHeight(30);
                table_iReceiptDetails.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                table_iReceiptDetailsMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(table_iReceiptDetails);

                javax.swing.GroupLayout panelCustom3Layout = new javax.swing.GroupLayout(panelCustom3);
                panelCustom3.setLayout(panelCustom3Layout);
                panelCustom3Layout.setHorizontalGroup(
                        panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustom3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))
                );
                panelCustom3Layout.setVerticalGroup(
                        panelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustom3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
                );

                add(panelCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 105, -1, 610));

                panelCustom4.setPreferredSize(new java.awt.Dimension(248, 612));
                panelCustom4.setRoundBottomLeft(10);
                panelCustom4.setRoundBottomRigt(10);
                panelCustom4.setRoundTopLeft(10);
                panelCustom4.setRoundTopRigt(10);
                panelCustom4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tf_iReceiptId.setEditable(false);
                tf_iReceiptId.setBackground(new java.awt.Color(204, 204, 204));
                tf_iReceiptId.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                tf_iReceiptId.setPreferredSize(new java.awt.Dimension(210, 33));
                tf_iReceiptId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tf_iReceiptIdActionPerformed(evt);
                        }
                });
                jPanel1.add(tf_iReceiptId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 40));

                jLabel4.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
                jLabel4.setText("Mã phiếu nhập");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                panelCustom4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 21, -1, -1));

                jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tf_bookId.setEditable(false);
                tf_bookId.setBackground(new java.awt.Color(204, 204, 204));
                tf_bookId.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                tf_bookId.setPreferredSize(new java.awt.Dimension(210, 33));
                tf_bookId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tf_bookIdActionPerformed(evt);
                        }
                });
                jPanel3.add(tf_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 40));

                jLabel5.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
                jLabel5.setText("Mã sách");
                jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                panelCustom4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 90, -1, -1));

                jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tf_bookName.setEditable(false);
                tf_bookName.setBackground(new java.awt.Color(204, 204, 204));
                tf_bookName.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                tf_bookName.setPreferredSize(new java.awt.Dimension(210, 33));
                tf_bookName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tf_bookNameActionPerformed(evt);
                        }
                });
                jPanel4.add(tf_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 40));

                jLabel6.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
                jLabel6.setText("Tên sách");
                jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                panelCustom4.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 159, -1, -1));

                jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tf_quantity.setEditable(false);
                tf_quantity.setBackground(new java.awt.Color(204, 204, 204));
                tf_quantity.setFont(new java.awt.Font("Lexend", 0, 14)); // NOI18N
                tf_quantity.setPreferredSize(new java.awt.Dimension(210, 33));
                tf_quantity.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tf_quantityActionPerformed(evt);
                        }
                });
                jPanel5.add(tf_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 40));

                jLabel7.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
                jLabel7.setText("Số lượng nhập");
                jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

                panelCustom4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 228, -1, -1));

                add(panelCustom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 103, -1, -1));

                lbl_backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-small-left.png"))); // NOI18N
                add(lbl_backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 24, -1, -1));
        }// </editor-fold>//GEN-END:initComponents

    private void tf_iReceiptIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_iReceiptIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_iReceiptIdActionPerformed

    private void tf_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookIdActionPerformed

    private void tf_bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookNameActionPerformed

    private void tf_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_quantityActionPerformed

        private void table_iReceiptDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_iReceiptDetailsMouseClicked
                // TODO add your handling code here:
		tf_iReceiptId.setText(tableModel.getValueAt(table_iReceiptDetails.getSelectedRow(), 0).toString());
		tf_bookId.setText(tableModel.getValueAt(table_iReceiptDetails.getSelectedRow(), 1).toString());
		tf_bookName.setText(tableModel.getValueAt(table_iReceiptDetails.getSelectedRow(), 2).toString());
		tf_quantity.setText(tableModel.getValueAt(table_iReceiptDetails.getSelectedRow(), 3).toString());
        }//GEN-LAST:event_table_iReceiptDetailsMouseClicked


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lbl_backBtn;
        private Custom.PanelCustom panelCustom3;
        private Custom.PanelCustom panelCustom4;
        private javax.swing.JTable table_iReceiptDetails;
        private com.nhom08.bookstore.GUI.TextFieldCustom tf_bookId;
        private com.nhom08.bookstore.GUI.TextFieldCustom tf_bookName;
        private com.nhom08.bookstore.GUI.TextFieldCustom tf_iReceiptId;
        private com.nhom08.bookstore.GUI.TextFieldCustom tf_quantity;
        // End of variables declaration//GEN-END:variables
}
