/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

import com.nhom08.bookstore.DAO.EmployeeDetailDAO;
import com.nhom08.bookstore.DAO.ShiftDAO;
import com.nhom08.bookstore.Models.EmployeeModel;

/**
 *
 * @author quythuong
 */
public class panel_employeeDetails extends javax.swing.JPanel {

    /**
     * Creates new form panel_employeeDetails
     */
    private EmployeeDetailDAO employeeDetailDAO;
    private ShiftDAO shiftDAO;
    public panel_employeeDetails() {
        initComponents();
        displayData();
    }

    private void reset(){
        txt_maNV.setEnabled(false);
        txt_tenNV.setEnabled(false);
        cb_gioiTinh.setEnabled(false);
        txt_chucVu.setEnabled(false);
        txt_diaChi.setEnabled(false);
        txt_tenTaiKhoan.setEnabled(false);
        txt_matKhau.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustom2 = new Custom.PanelCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        panelCustom3 = new Custom.PanelCustom();
        jPanel1 = new javax.swing.JPanel();
        txt_maNV = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_tenNV = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cb_gioiTinh = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txt_diaChi = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_chucVu = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jPanel8 = new javax.swing.JPanel();
        txt_matKhau = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txt_tenTaiKhoan = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel13 = new javax.swing.JLabel();
        btn_huy = new javax.swing.JLabel();
        btn_save = new javax.swing.JLabel();
        btn_edit = new Custom.ButtonCustom();

        setBackground(new java.awt.Color(255, 254, 251));
        setPreferredSize(new java.awt.Dimension(1280, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustom2.setPreferredSize(new java.awt.Dimension(695, 515));
        panelCustom2.setRoundBottomLeft(10);
        panelCustom2.setRoundBottomRigt(10);
        panelCustom2.setRoundTopLeft(10);
        panelCustom2.setRoundTopRigt(10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Ca", "Thứ", "Chúc vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelCustom2Layout = new javax.swing.GroupLayout(panelCustom2);
        panelCustom2.setLayout(panelCustom2Layout);
        panelCustom2Layout.setHorizontalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        panelCustom2Layout.setVerticalGroup(
            panelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        add(panelCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 620));

        jLabel3.setFont(new java.awt.Font("Lexend", 0, 30)); // NOI18N
        jLabel3.setText("Account Management");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        panelCustom3.setPreferredSize(new java.awt.Dimension(248, 612));
        panelCustom3.setRoundBottomLeft(10);
        panelCustom3.setRoundBottomRigt(10);
        panelCustom3.setRoundTopLeft(10);
        panelCustom3.setRoundTopRigt(10);
        panelCustom3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_maNV.setAutoscrolls(false);
        txt_maNV.setEnabled(false);
        txt_maNV.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_maNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNVActionPerformed(evt);
            }
        });
        txt_maNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_maNVKeyTyped(evt);
            }
        });
        jPanel1.add(txt_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel4.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel4.setText("Mã NV");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tenNV.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_tenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenNVActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel5.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel5.setText("Tên");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel6.setText("Giới tính");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cb_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Không xác định" }));
        jPanel4.add(cb_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 40));

        panelCustom3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 70));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_diaChi.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_diaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diaChiActionPerformed(evt);
            }
        });
        jPanel5.add(txt_diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel7.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel7.setText("Địa chỉ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 70));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel8.setText("Chức vụ");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        txt_chucVu.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_chucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chucVuActionPerformed(evt);
            }
        });
        jPanel6.add(txt_chucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        panelCustom3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 70));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_matKhau.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauActionPerformed(evt);
            }
        });
        jPanel8.add(txt_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel10.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel10.setText("Mật khẩu");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 70));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tenTaiKhoan.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_tenTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenTaiKhoanActionPerformed(evt);
            }
        });
        jPanel9.add(txt_tenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 44));

        jLabel13.setFont(new java.awt.Font("Lexend", 0, 15)); // NOI18N
        jLabel13.setText("Tên tài khoản");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelCustom3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 70));

        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancle.png"))); // NOI18N
        btn_huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_huyMouseClicked(evt);
            }
        });
        panelCustom3.add(btn_huy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, 38));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        panelCustom3.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 40, 38));

        add(panelCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, -1));

        btn_edit.setBackground(new java.awt.Color(217, 217, 217));
        btn_edit.setBorder(null);
        btn_edit.setText("Edit");
        btn_edit.setBorderColor(new java.awt.Color(217, 217, 217));
        btn_edit.setFont(new java.awt.Font("Lexend", 0, 24)); // NOI18N
        btn_edit.setPreferredSize(new java.awt.Dimension(160, 42));
        btn_edit.setRadius(20);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txt_maNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNVActionPerformed

    private void txt_maNVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maNVKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_maNVKeyTyped

    private void txt_tenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenNVActionPerformed

    private void txt_diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaChiActionPerformed

    private void txt_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauActionPerformed

    private void txt_tenTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenTaiKhoanActionPerformed

    private void btn_huyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_huyMouseClicked
        // TODO add your handling code here:
        // Xóa nội dung của các trường nhập liệu
        
    }//GEN-LAST:event_btn_huyMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // Lấy thông tin từ các trường nhập liệu
        txt_maNV.setEnabled(false);
        txt_tenNV.setEnabled(true);
        cb_gioiTinh.setEnabled(true);
        txt_chucVu.setEnabled(false);
        txt_diaChi.setEnabled(true);
        txt_tenTaiKhoan.setEnabled(false);
        txt_matKhau.setEnabled(true);
        

    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // Lấy thông tin từ các trường nhập liệu
        String tenNV = txt_tenNV.getText();
        String gioiTinh = (String) cb_gioiTinh.getSelectedItem();
        String diaChi = txt_diaChi.getText();
        String matKhauMoi = txt_matKhau.getText().isEmpty() ? null : txt_matKhau.getText();

        try {
            // Gọi phương thức updatePersonalInfo của PersonalInfoDAO để cập nhật thông tin cá nhân trong CSDL
            employeeDetailDAO.updateInfo(tenNV, gioiTinh, diaChi, matKhauMoi);
            displayData();
            reset();
        } 
        catch (Exception ex){
            // Xử lý khi có lỗi SQL
            ex.printStackTrace(); // In stack trace của lỗi để xác định vấn đề cụ thể
            // Hiển thị thông báo lỗi cho người dùng
        }
        
    }//GEN-LAST:event_btn_saveMouseClicked

    private void txt_chucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chucVuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.ButtonCustom btn_edit;
    private javax.swing.JLabel btn_huy;
    private javax.swing.JLabel btn_save;
    private javax.swing.JComboBox<String> cb_gioiTinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private Custom.PanelCustom panelCustom2;
    private Custom.PanelCustom panelCustom3;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_chucVu;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_diaChi;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_maNV;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_matKhau;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_tenNV;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_tenTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void displayData() {
        EmployeeModel employee = employeeDetailDAO.getInfo();
        txt_chucVu.setText(employee.getPosition());
        txt_tenNV.setText(employee.getPosition());
        txt_maNV.setText(employee.getPosition());
        txt_matKhau.setText(employee.getPosition());
        cb_gioiTinh.setSelectedItem(employee.getSex());
        txt_diaChi.setText(employee.getAddress());
        txt_tenTaiKhoan.setText(employee.getAccount());

    }
}
