/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom08.bookstore.GUI.FunctionalPanels;

import com.nhom08.bookstore.DAO.AccountDAO;
import com.nhom08.bookstore.Models.AccountModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author quythuong
 */
public class panel_accounts extends javax.swing.JPanel {

    /**
     * Creates new form panel_accounts
     */
    public panel_accounts() {
        initComponents();

        try {
            hienThiThongTin();
        } catch (SQLException ex) {
            // Xử lý khi có lỗi xảy ra
            ex.printStackTrace();
        }
    }

    // Hàm hiển thị thông tin lên các TextFieldCustom
    private void hienThiThongTin() throws SQLException {
        AccountDAO accountDAO = new AccountDAO();
        AccountModel account = accountDAO.xemThongTinCaNhan();
        txt_manv.setText(account.getManv());
        txt_username.setText(account.getUsername());
        txt_tennv.setText(account.getTennv());
        txt_password.setText(account.getPassword());
        txt_diachi.setText(account.getDiachi());
        txt_gioitinh.setText(account.getGioitinh());
        txt_chucvu.setText(account.getRole());
        txt_cap.setText(account.getCap());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelCustom1 = new Custom.PanelCustom();
        btn_edit = new Custom.ButtonCustom();
        btn_delete = new Custom.ButtonCustom();
        panelCustom3 = new Custom.PanelCustom();
        jPanel1 = new javax.swing.JPanel();
        txt_manv = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_username = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_tennv = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_password = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_diachi = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txt_gioitinh = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txt_chucvu = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txt_cap = new com.nhom08.bookstore.GUI.TextFieldCustom();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 254, 251));
        setPreferredSize(new java.awt.Dimension(1056, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lexend", 0, 30)); // NOI18N
        jLabel2.setText("Accounts Management");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 25, -1, -1));

        panelCustom1.setPreferredSize(new java.awt.Dimension(695, 68));
        panelCustom1.setRoundBottomLeft(30);
        panelCustom1.setRoundBottomRigt(30);
        panelCustom1.setRoundTopLeft(30);
        panelCustom1.setRoundTopRigt(30);
        panelCustom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setBackground(new java.awt.Color(217, 217, 217));
        btn_edit.setBorder(null);
        btn_edit.setText("Edit");
        btn_edit.setBorderColor(new java.awt.Color(217, 217, 217));
        btn_edit.setFont(new java.awt.Font("Lexend", 0, 22)); // NOI18N
        btn_edit.setPreferredSize(new java.awt.Dimension(160, 42));
        btn_edit.setRadius(20);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        panelCustom1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btn_delete.setBackground(new java.awt.Color(217, 217, 217));
        btn_delete.setBorder(null);
        btn_delete.setText("Delete");
        btn_delete.setBorderColor(new java.awt.Color(217, 217, 217));
        btn_delete.setFont(new java.awt.Font("Lexend", 0, 22)); // NOI18N
        btn_delete.setPreferredSize(new java.awt.Dimension(160, 42));
        btn_delete.setRadius(20);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        panelCustom1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 200, 520));

        panelCustom3.setPreferredSize(new java.awt.Dimension(248, 612));
        panelCustom3.setRoundBottomLeft(30);
        panelCustom3.setRoundBottomRigt(30);
        panelCustom3.setRoundTopLeft(30);
        panelCustom3.setRoundTopRigt(30);
        panelCustom3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_manv.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_manv.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manvActionPerformed(evt);
            }
        });
        jPanel1.add(txt_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel4.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel4.setText("Mã Nhân Viên :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, 30));

        panelCustom3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancle.png"))); // NOI18N
        panelCustom3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 556, 40, 38));

        jPanel2.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_username.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel5.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel5.setText("Username :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 30));

        panelCustom3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 640, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tennv.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_tennv.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_tennv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tennvActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel6.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel6.setText("Tên Nhân Viên :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 30));

        panelCustom3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 640, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_password.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_password.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel4.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel7.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel7.setText("Password :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 30));

        panelCustom3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 640, -1));

        jPanel5.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_diachi.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_diachi.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diachiActionPerformed(evt);
            }
        });
        jPanel5.add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel8.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel8.setText("Địa Chỉ :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 30));

        panelCustom3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 640, -1));

        jPanel7.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_gioitinh.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_gioitinh.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_gioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gioitinhActionPerformed(evt);
            }
        });
        jPanel7.add(txt_gioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel10.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel10.setText("Giới Tính :");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 30));

        panelCustom3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 640, -1));

        jPanel6.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_chucvu.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_chucvu.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_chucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chucvuActionPerformed(evt);
            }
        });
        jPanel6.add(txt_chucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel9.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel9.setText("Chức Vụ :");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 30));

        panelCustom3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 640, -1));

        jPanel8.setPreferredSize(new java.awt.Dimension(210, 52));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cap.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        txt_cap.setPreferredSize(new java.awt.Dimension(210, 33));
        txt_cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_capActionPerformed(evt);
            }
        });
        jPanel8.add(txt_cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 40));

        jLabel12.setFont(new java.awt.Font("Lexend", 0, 20)); // NOI18N
        jLabel12.setText("Cấp :");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 30));

        panelCustom3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 640, -1));

        add(panelCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 650, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manvActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            // Lấy thông tin mới từ các TextFieldCustom
            String tenNV = txt_tennv.getText();
            String gioiTinh = txt_gioitinh.getText();
            String diaChi = txt_diachi.getText();
            String password = txt_password.getText();

            // Tạo đối tượng AccountModel mới với thông tin cập nhật
            AccountModel account = new AccountModel();
            account.setTennv(tenNV);
            account.setGioitinh(gioiTinh);
            account.setDiachi(diaChi);
            account.setPassword(password);

            // Tạo một đối tượng AccountDAO để thực hiện cập nhật
            AccountDAO accountDAO = new AccountDAO();
            boolean updateResult = accountDAO.update(account);

            if (updateResult) {
                // Nếu cập nhật thành công, hiển thị thông báo cho người dùng
                JOptionPane.showMessageDialog(this, "Thông tin cá nhân đã được cập nhật thành công!");
            } else {
                // Nếu cập nhật không thành công, hiển thị thông báo lỗi cho người dùng
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi cập nhật thông tin cá nhân. Vui lòng thử lại sau.");
            }

        } catch (SQLException ex) {
            // Xử lý khi có lỗi xảy ra
            ex.printStackTrace();
            }    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_tennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tennvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tennvActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diachiActionPerformed

    private void txt_chucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chucvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chucvuActionPerformed

    private void txt_gioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gioitinhActionPerformed

    private void txt_capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_capActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_capActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.ButtonCustom btn_delete;
    private Custom.ButtonCustom btn_edit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private Custom.PanelCustom panelCustom1;
    private Custom.PanelCustom panelCustom3;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_cap;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_chucvu;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_diachi;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_gioitinh;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_manv;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_password;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_tennv;
    private com.nhom08.bookstore.GUI.TextFieldCustom txt_username;
    // End of variables declaration//GEN-END:variables
}
